services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: supermarket_app_dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
